astra_db:
  collection_name: "ecommercedata"
  auth:
    endpoint_env: "ASTRA_DB_API_ENDPOINT"
    token_env: "ASTRA_DB_APPLICATION_TOKEN"
    keyspace_env: "ASTRA_DB_KEYSPACE"

embedding_model:
  provider: "huggingface"
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  device: "cpu"
  normalize_embeddings: true

retriever:
  top_k: 4

llm:
  active_provider: "groq"   # openai | google | groq

  groq:
    provider: "groq"
    api_key_env: "GROQ_API_KEY"
    model_name: "llama-3.1-8b-instant"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    api_key_env: "GOOGLE_API_KEY"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048

  openai:
    provider: "openai"
    api_key_env: "OPENAI_API_KEY"
    model_name: "gpt-4o"
    temperature: 0
    max_output_tokens: 2048
