SELECT RECORD_TYPE, COUNT(*) AS CompanyLikeCount
FROM dbo.Bronze_PII_Table_Raw
WHERE PERSON_LAST_NAME LIKE '%LLC%'
   OR PERSON_LAST_NAME LIKE '%INC%'
   OR PERSON_LAST_NAME LIKE '%CORP%'
   OR PERSON_LAST_NAME LIKE '%CO.%'
   OR PERSON_LAST_NAME LIKE '%DOLLAR%'
   OR PERSON_LAST_NAME LIKE '%SERVICE%'
   OR PERSON_LAST_NAME LIKE '%STORAGE%'
   OR PERSON_LAST_NAME LIKE '%DISTRICT%'
   OR PERSON_LAST_NAME LIKE '%FIRE DIST%'
   OR PERSON_LAST_NAME LIKE '[0-9]%'
GROUP BY RECORD_TYPE
ORDER BY CompanyLikeCount DESC;


SELECT
    SUM(CASE WHEN PERSON_FIRST_NAME LIKE '%LLC%' OR PERSON_FIRST_NAME LIKE '%INC%' 
         OR PERSON_FIRST_NAME LIKE '%CORP%' OR PERSON_FIRST_NAME LIKE '%DOLLAR%'
         OR PERSON_FIRST_NAME LIKE '%SERVICE%' OR PERSON_FIRST_NAME LIKE '%STORAGE%'
         OR PERSON_FIRST_NAME LIKE '%DISTRICT%' OR PERSON_FIRST_NAME LIKE '[0-9]%'
         THEN 1 ELSE 0 END) AS CompanyLike_FirstName,
    SUM(CASE WHEN PERSON_MIDDLE_NAME LIKE '%LLC%' OR PERSON_MIDDLE_NAME LIKE '%INC%'
         OR PERSON_MIDDLE_NAME LIKE '%CORP%' OR PERSON_MIDDLE_NAME LIKE '%DOLLAR%'
         OR PERSON_MIDDLE_NAME LIKE '%SERVICE%' OR PERSON_MIDDLE_NAME LIKE '%STORAGE%'
         OR PERSON_MIDDLE_NAME LIKE '%DISTRICT%' OR PERSON_MIDDLE_NAME LIKE '[0-9]%'
         THEN 1 ELSE 0 END) AS CompanyLike_MiddleName
FROM dbo.Bronze_PII_Table_Raw
WHERE RECORD_TYPE = 'Person';


