SELECT
    COUNT(*) AS TotalHexGarbageRecords,
    SUM(CASE WHEN PERSON_FIRST_NAME IS NOT NULL AND LTRIM(RTRIM(PERSON_FIRST_NAME)) <> '' THEN 1 ELSE 0 END) AS HasFirstName,
    SUM(CASE WHEN PERSON_MIDDLE_NAME IS NOT NULL AND LTRIM(RTRIM(PERSON_MIDDLE_NAME)) <> '' THEN 1 ELSE 0 END) AS HasMiddleName,
    SUM(CASE WHEN PERSON_LAST_NAME IS NOT NULL AND LTRIM(RTRIM(PERSON_LAST_NAME)) <> '' THEN 1 ELSE 0 END) AS HasLastName,
    SUM(CASE WHEN PERSON_FULL_NAME IS NOT NULL AND LTRIM(RTRIM(PERSON_FULL_NAME)) <> '' THEN 1 ELSE 0 END) AS HasFullName,
    SUM(CASE WHEN PERSON_EMAIL IS NOT NULL AND LTRIM(RTRIM(PERSON_EMAIL)) <> '' THEN 1 ELSE 0 END) AS HasEmail,
    SUM(CASE WHEN PERSON_PHONE IS NOT NULL AND LTRIM(RTRIM(PERSON_PHONE)) <> '' THEN 1 ELSE 0 END) AS HasPhone,
    SUM(CASE WHEN PERSON_TAX_ID IS NOT NULL AND LTRIM(RTRIM(PERSON_TAX_ID)) <> '' THEN 1 ELSE 0 END) AS HasTaxID,
    SUM(CASE WHEN PERSON_ID IS NOT NULL AND LTRIM(RTRIM(PERSON_ID)) <> '' THEN 1 ELSE 0 END) AS HasPersonID,
    SUM(CASE WHEN PERSON_ID_TYPE IS NOT NULL AND LTRIM(RTRIM(PERSON_ID_TYPE)) <> '' THEN 1 ELSE 0 END) AS HasPersonIDType,
    SUM(CASE WHEN PERSON_COMPANY IS NOT NULL AND LTRIM(RTRIM(PERSON_COMPANY)) <> '' THEN 1 ELSE 0 END) AS HasCompany,
    SUM(CASE WHEN PERSON_ADDRESS_STREET IS NOT NULL AND LTRIM(RTRIM(PERSON_ADDRESS_STREET)) <> '' THEN 1 ELSE 0 END) AS HasStreet,
    SUM(CASE WHEN PERSON_ADDRESS_CITY IS NOT NULL AND LTRIM(RTRIM(PERSON_ADDRESS_CITY)) <> '' THEN 1 ELSE 0 END) AS HasCity,
    SUM(CASE WHEN PERSON_ADDRESS_STATE IS NOT NULL AND LTRIM(RTRIM(PERSON_ADDRESS_STATE)) <> '' THEN 1 ELSE 0 END) AS HasState,
    SUM(CASE WHEN PERSON_ADDRESS_ZIP IS NOT NULL AND LTRIM(RTRIM(PERSON_ADDRESS_ZIP)) <> '' THEN 1 ELSE 0 END) AS HasZip,
    SUM(CASE WHEN PERSON_ADDRESS_COUNTRY IS NOT NULL AND LTRIM(RTRIM(PERSON_ADDRESS_COUNTRY)) <> '' THEN 1 ELSE 0 END) AS HasCountry,
    SUM(CASE WHEN FULL_CREDIT_CARD IS NOT NULL AND LTRIM(RTRIM(FULL_CREDIT_CARD)) <> '' THEN 1 ELSE 0 END) AS HasCreditCard,
    SUM(CASE WHEN BANK_ACCOUNT_NUMBER IS NOT NULL AND LTRIM(RTRIM(BANK_ACCOUNT_NUMBER)) <> '' THEN 1 ELSE 0 END) AS HasBankAccount,
    SUM(CASE WHEN DRIVERS_LICENSE IS NOT NULL AND LTRIM(RTRIM(DRIVERS_LICENSE)) <> '' THEN 1 ELSE 0 END) AS HasDriversLicense,
    SUM(CASE WHEN PASSPORT IS NOT NULL AND LTRIM(RTRIM(PASSPORT)) <> '' THEN 1 ELSE 0 END) AS HasPassport,
    SUM(CASE WHEN GOVERNMENT_ID IS NOT NULL AND LTRIM(RTRIM(GOVERNMENT_ID)) <> '' THEN 1 ELSE 0 END) AS HasGovernmentID
FROM dbo.Bronze_PII_Table_Raw
WHERE PERSON_ADDRESS_FULL LIKE '0x%';

SELECT TOP 20
    PERSON_ADDRESS_FULL,
    PERSON_FULL_NAME, PERSON_FIRST_NAME, PERSON_MIDDLE_NAME, PERSON_LAST_NAME,
    PERSON_EMAIL, PERSON_PHONE, PERSON_TAX_ID, PERSON_ID, PERSON_ID_TYPE, PERSON_COMPANY,
    PERSON_ADDRESS_STREET, PERSON_ADDRESS_CITY, PERSON_ADDRESS_STATE, PERSON_ADDRESS_ZIP, PERSON_ADDRESS_COUNTRY,
    FULL_CREDIT_CARD, BANK_ACCOUNT_NUMBER, DRIVERS_LICENSE, PASSPORT, GOVERNMENT_ID,
    PERSON_DATE_OF_BIRTH, RECORD_TYPE
FROM dbo.Bronze_PII_Table_Raw
WHERE PERSON_ADDRESS_FULL LIKE '0x%'
ORDER BY NEWID();
