SELECT TOP 30
    PERSON_FULL_NAME,
    PERSON_FIRST_NAME,
    PERSON_MIDDLE_NAME,
    PERSON_LAST_NAME
FROM dbo.Bronze_PII_Table_Raw
WHERE (PERSON_FULL_NAME IS NOT NULL AND PERSON_FULL_NAME NOT LIKE '%[a-zA-Z0-9]%')
   OR (PERSON_FIRST_NAME IS NOT NULL AND PERSON_FIRST_NAME NOT LIKE '%[a-zA-Z0-9]%')
   OR (PERSON_MIDDLE_NAME IS NOT NULL AND PERSON_MIDDLE_NAME NOT LIKE '%[a-zA-Z0-9]%')
   OR (PERSON_LAST_NAME IS NOT NULL AND PERSON_LAST_NAME NOT LIKE '%[a-zA-Z0-9]%')
ORDER BY NEWID();
